#!/usr/bin/env bash
#looks for user in /etc/passwd if not found creates user

if [ $# != 1 ]
then
    exit 1
    fi
    if [ "$(cut -d: -f1 /etc/passwd | grep "$1")" != "$1" ]
    then
        exit 1
	else
	    sudo -u "$1" whoami
	    fi
